import 'package:flutter/material.dart';

import '../core/battle_layout_v4.dart';
import '../core/combat_state_v4.dart';
import '../models/battle_v4_models.dart';
import 'battle_status_strip_v4.dart';
import 'hex_board_painter_v4.dart';
import 'radial_command_v4.dart';

class HexBoardV4 extends StatelessWidget {
  const HexBoardV4({super.key,required this.units,required this.activeUnit,required this.onBoardTap,required this.onCategory,required this.onSkill,required this.onBack,required this.onMove,required this.onUnit,required this.columns,required this.rows,required this.terrain,required this.telegraphHexes,required this.targetHexes,required this.reachableHexes,required this.opportunityWarningHexes,required this.interactionMode,required this.selectedCategory,required this.skills,required this.selectedSkillId,required this.moveEnabled});
  final List<V4BattleUnit> units; final V4BattleUnit activeUnit; final ValueChanged<HexCoord> onBoardTap; final ValueChanged<V4ActionCategory> onCategory; final ValueChanged<String> onSkill; final VoidCallback onBack,onMove; final ValueChanged<String> onUnit; final int columns,rows; final Map<HexCoord,TerrainV4> terrain; final Set<HexCoord> telegraphHexes,targetHexes,reachableHexes,opportunityWarningHexes; final V4InteractionMode interactionMode; final V4ActionCategory selectedCategory; final List<V4SkillChoice> skills; final String? selectedSkillId; final bool moveEnabled;
  @override Widget build(BuildContext context)=>LayoutBuilder(builder:(context,constraints){final geometry=HexGeometryV4(Size(constraints.maxWidth,constraints.maxHeight),columns:columns,rows:rows),activeCenter=geometry.center(activeUnit.anchor);return GestureDetector(behavior:HitTestBehavior.opaque,onTapUp:(d){final c=geometry.hitTest(d.localPosition);if(c!=null)onBoardTap(c);},child:Stack(clipBehavior:Clip.none,children:[Positioned.fill(child:CustomPaint(painter:HexBoardPainterV4(geometry:geometry,units:units,terrain:terrain,targetHexes:targetHexes,telegraphHexes:telegraphHexes,reachableHexes:reachableHexes,opportunityWarningHexes:opportunityWarningHexes,movementMode:interactionMode==V4InteractionMode.move))),for(final u in units)_UnitSprite(unit:u,geometry:geometry,selected:u.id==activeUnit.id,onTap:()=>onUnit(u.id)),if(activeUnit.team==V4Team.party)...[if(interactionMode==V4InteractionMode.command)Positioned.fill(child:RadialCommandV4(center:activeCenter.translate(0,-22),radius:BattleLayoutV4.radialRadius,selected:selectedCategory,onSelected:onCategory)),if(interactionMode==V4InteractionMode.skill)Positioned.fill(child:SkillRadialV4(center:activeCenter.translate(0,-22),radius:BattleLayoutV4.radialRadius,skills:skills,selectedId:selectedSkillId,onSkill:onSkill,onBack:onBack)),RadialMoveButtonV4(center:activeCenter.translate(0,-22),radius:BattleLayoutV4.radialRadius,active:interactionMode==V4InteractionMode.move,enabled:moveEnabled||interactionMode==V4InteractionMode.move,onTap:interactionMode==V4InteractionMode.move?onBack:onMove)]]));});
}
class _UnitSprite extends StatelessWidget{const _UnitSprite({required this.unit,required this.geometry,required this.selected,required this.onTap});final V4BattleUnit unit;final HexGeometryV4 geometry;final bool selected;final VoidCallback onTap;@override Widget build(BuildContext context){final center=geometry.center(unit.anchor),boardH=geometry.size.height;final visualH=switch(unit.size){V4UnitSize.normal=>boardH*.23,V4UnitSize.large3=>boardH*.37,V4UnitSize.huge7=>boardH*.47},visualW=visualH*(unit.size==V4UnitSize.normal?.72:1.05);return Positioned(left:center.dx-visualW/2,top:center.dy-visualH+geometry.hexHeight*.12-20,width:visualW,height:visualH+40,child:GestureDetector(behavior:HitTestBehavior.translucent,onTap:onTap,child:Column(children:[SizedBox(height:20,child:FittedBox(fit:BoxFit.scaleDown,child:BattleStatusStripV4(statuses:unit.statuses,barrier:unit.barrier,compact:true))),Expanded(child:Stack(alignment:Alignment.bottomCenter,children:[if(selected)Positioned(bottom:0,child:Container(width:visualW*.72,height:12,decoration:BoxDecoration(border:Border.all(color:const Color(0xFF73B8FF),width:2),borderRadius:BorderRadius.circular(50)))),_art()])),const SizedBox(height:2),ClipRRect(borderRadius:BorderRadius.circular(4),child:LinearProgressIndicator(minHeight:4,value:unit.hpRatio.clamp(0.0,1.0).toDouble(),backgroundColor:const Color(0xC922242C),valueColor:AlwaysStoppedAnimation(unit.team==V4Team.party?const Color(0xFF5DBB72):const Color(0xFFD45E61))))])));}Widget _art()=>unit.assetPath!=null?Image.asset(unit.assetPath!,fit:BoxFit.contain,alignment:Alignment.bottomCenter,filterQuality:FilterQuality.medium,errorBuilder:(_,__,___)=>_placeholder()):_placeholder();Widget _placeholder()=>Align(alignment:Alignment.bottomCenter,child:Container(width:30,height:54,decoration:BoxDecoration(color:unit.team==V4Team.party?const Color(0xFF496B9B):const Color(0xFF8B4E4E),borderRadius:const BorderRadius.vertical(top:Radius.circular(18),bottom:Radius.circular(6)),border:Border.all(color:Colors.white54)),alignment:Alignment.center,child:Text(unit.name.characters.first,style:const TextStyle(fontWeight:FontWeight.bold))));}
