part of 'battle_preview_controller_v4.dart';

extension BattlePreviewCommandV4 on BattlePreviewControllerV4 {
  List<V4SkillChoice> get currentSkills { final actor=activeCombatUnit; if(actor==null||actor.team!=CombatTeamV4.party)return const[]; return _skillsFor(actor.id,selectedCategory); }
  bool get canEnterMoveMode { final actor=activeCombatUnit; return actor!=null&&actor.team==CombatTeamV4.party&&engine.activationOpen&&!engine.movementUsedThisActivation&&!actor.has(StatusTypeV4.rooted); }
  bool get canCommit=>interactionMode==V4InteractionMode.skill&&selectedSkillId!=null&&!engine.battleOver;
  Set<HexCoord> get reachableHexes { final actor=activeCombatUnit; if(interactionMode!=V4InteractionMode.move||actor==null||actor.team!=CombatTeamV4.party)return const{}; final map=engine.board.reachable(unit:actor,units:engine.units);return map.keys.where((c)=>c!=actor.anchor).toSet(); }
  Set<HexCoord> get opportunityWarningHexes=>{for(final hex in reachableHexes)if(_opportunityCount(hex)>0)hex};
  Set<HexCoord> get targetHexes {final actor=activeCombatUnit,skill=selectedSkillId;if(actor==null||skill==null||interactionMode!=V4InteractionMode.skill)return const{};final spell=_spellForSkill(skill);if(spell!=null){final target=spell.shape==TargetShapeV4.self?actor.anchor:selectedTarget;return const TargetResolverV4().resolveHexes(spell:spell,caster:actor,target:target,board:engine.board);}if(skill=='kael.guard'||skill=='item.hp_potion')return{actor.anchor};return{selectedTarget};}
  void selectCategory(V4ActionCategory category){selectedCategory=category;final skills=_skillsFor(activeCombatUnit?.id,category);selectedSkillId=skills.isEmpty?null:skills.first.id;interactionMode=V4InteractionMode.skill;notifyListeners();}
  void selectSkill(String id){if(!currentSkills.any((s)=>s.id==id))return;selectedSkillId=id;notifyListeners();}
  void backToCategories(){interactionMode=V4InteractionMode.command;selectedSkillId=null;notifyListeners();}
  void enterMoveMode(){if(!canEnterMoveMode)return;interactionMode=V4InteractionMode.move;selectedSkillId=null;selectedTarget=activeCombatUnit!.anchor;notifyListeners();}
  void handleBoardTap(HexCoord target){if(interactionMode==V4InteractionMode.move){selectedTarget=target;if(!reachableHexes.contains(target)){notifyListeners();return;}final moved=engine.moveActiveTo(target);if(moved){interactionMode=V4InteractionMode.command;selectedSkillId=null;}notifyListeners();return;}selectTarget(target);}
  void commit(){if(!canCommit)return;var actor=engine.activeUnit;actor??=engine.beginNextActivation();if(actor==null||!engine.activationOpen)return;if(actor.team==CombatTeamV4.enemy){policy.takeActivation(engine);_advanceEnemyTurns();notifyListeners();return;}try{_commitSkill(actor,selectedSkillId!);}on StateError{notifyListeners();return;}_resetCommandUi();_advanceEnemyTurns();if(auto)_runAutoWindow();notifyListeners();}
  void _commitSkill(CombatUnitV4 actor,String skill){final spell=_spellForSkill(skill);if(spell!=null){engine.castSpellAction(casterId:actor.id,spell:spell,targetHex:spell.shape==TargetShapeV4.self?actor.anchor:selectedTarget);return;}final target=targetAt(selectedTarget);switch(skill){case'item.hp_potion':if(hpPotions<=0)throw StateError('no potion');engine.usePotion(actorId:actor.id,flatHeal:24,maxHpRatio:.15,baseDelay:90);hpPotions--;return;case'kael.quick':engine.kaelQuickSlash(targetId:_enemyTarget(target).id);return;case'kael.heavy':engine.kaelHeavyStrike(targetId:_enemyTarget(target).id);return;case'kael.pull':engine.kaelHookPull(targetId:_enemyTarget(target).id);return;case'kael.guard':engine.kaelGuardStance();return;case'nera.vital':engine.neraVitalStrike(targetId:_enemyTarget(target).id);return;case'nera.expose':engine.neraExposeWeakness(targetId:_enemyTarget(target).id);return;case'nera.smoke':engine.neraSmokeStep(selectedTarget);return;}throw StateError('unknown skill');}
  CombatUnitV4 _enemyTarget(CombatUnitV4? target){final actor=activeCombatUnit;if(target==null||actor==null||target.team==actor.team)throw StateError('invalid target');return target;}
  int _opportunityCount(HexCoord destination){final actor=activeCombatUnit;if(actor==null||destination==actor.anchor)return 0;var count=0;for(final enemy in engine.units){if(enemy.isKo||enemy.team==actor.team||!enemy.reactionAvailable)continue;if(engine.board.adjacent(enemy.anchor,actor.anchor)&&!engine.board.adjacent(enemy.anchor,destination))count++;}return count;}
}
List<V4SkillChoice> _skillsFor(String? actorId,V4ActionCategory category){if(actorId=='wizard')return switch(category){V4ActionCategory.attack=>const[V4SkillChoice(id:'wizard.dart',label:'비전 화살',shortLabel:'비전',category:V4ActionCategory.attack),V4SkillChoice(id:'wizard.fire_bolt',label:'화염탄',shortLabel:'화염',category:V4ActionCategory.attack),V4SkillChoice(id:'wizard.fireball',label:'화염구',shortLabel:'폭발',category:V4ActionCategory.attack)],V4ActionCategory.control=>const[V4SkillChoice(id:'wizard.bind',label:'비전 속박',shortLabel:'속박',category:V4ActionCategory.control)],V4ActionCategory.defense=>const[V4SkillChoice(id:'wizard.shield',label:'비전 방패',shortLabel:'방패',category:V4ActionCategory.defense)],V4ActionCategory.tool=>const[V4SkillChoice(id:'item.hp_potion',label:'HP Potion',shortLabel:'회복',category:V4ActionCategory.tool)]};if(actorId=='kael')return switch(category){V4ActionCategory.attack=>const[V4SkillChoice(id:'kael.quick',label:'빠른 베기',shortLabel:'속공',category:V4ActionCategory.attack),V4SkillChoice(id:'kael.heavy',label:'강타',shortLabel:'강타',category:V4ActionCategory.attack)],V4ActionCategory.control=>const[V4SkillChoice(id:'kael.pull',label:'갈고리 끌기',shortLabel:'끌기',category:V4ActionCategory.control)],V4ActionCategory.defense=>const[V4SkillChoice(id:'kael.guard',label:'방어 자세',shortLabel:'방어',category:V4ActionCategory.defense)],V4ActionCategory.tool=>const[V4SkillChoice(id:'item.hp_potion',label:'HP Potion',shortLabel:'회복',category:V4ActionCategory.tool)]};if(actorId=='nera')return switch(category){V4ActionCategory.attack=>const[V4SkillChoice(id:'nera.vital',label:'급소 찌르기',shortLabel:'급소',category:V4ActionCategory.attack)],V4ActionCategory.control=>const[V4SkillChoice(id:'nera.expose',label:'약점 노출',shortLabel:'노출',category:V4ActionCategory.control)],V4ActionCategory.defense=>const[V4SkillChoice(id:'nera.smoke',label:'연막 이동',shortLabel:'연막',category:V4ActionCategory.defense)],V4ActionCategory.tool=>const[V4SkillChoice(id:'item.hp_potion',label:'HP Potion',shortLabel:'회복',category:V4ActionCategory.tool)]};return const[];}
SpellActionV4? _spellForSkill(String skill)=>switch(skill){'wizard.dart'=>SpellCatalogV4.arcaneDart,'wizard.fire_bolt'=>SpellCatalogV4.fireBolt,'wizard.fireball'=>SpellCatalogV4.fireball,'wizard.bind'=>SpellCatalogV4.arcaneBind,'wizard.shield'=>SpellCatalogV4.arcaneShield,_=>null};
